/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    tenants: Tenant;
    tags: Tag;
    bookings: Booking;
    orders: Order;
    invoices: Invoice;
    reviews: Review;
    conversations: Conversation;
    messages: Message;
    payment_profiles: PaymentProfile;
    email_event_logs: EmailEventLog;
    commission_events: CommissionEvent;
    commission_statements: CommissionStatement;
    promotions: Promotion;
    promotion_counters: PromotionCounter;
    promotion_allocations: PromotionAllocation;
    support_chat_threads: SupportChatThread;
    support_chat_messages: SupportChatMessage;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      subcategories: 'categories';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    payment_profiles: PaymentProfilesSelect<false> | PaymentProfilesSelect<true>;
    email_event_logs: EmailEventLogsSelect<false> | EmailEventLogsSelect<true>;
    commission_events: CommissionEventsSelect<false> | CommissionEventsSelect<true>;
    commission_statements: CommissionStatementsSelect<false> | CommissionStatementsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    promotion_counters: PromotionCountersSelect<false> | PromotionCountersSelect<true>;
    promotion_allocations: PromotionAllocationsSelect<false> | PromotionAllocationsSelect<true>;
    support_chat_threads: SupportChatThreadsSelect<false> | SupportChatThreadsSelect<true>;
    support_chat_messages: SupportChatMessagesSelect<false> | SupportChatMessagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'de' | 'fr' | 'it' | 'es' | 'pt' | 'pl' | 'ro' | 'uk';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * App username (set once on create).
   */
  username: string;
  /**
   * Raw username from Clerk (for reference only).
   */
  clerkUsername?: string | null;
  usernameSource?: ('app' | 'clerk') | null;
  /**
   * When username was set.
   */
  usernameSyncedAt?: string | null;
  email?: string | null;
  clerkUserId?: string | null;
  /**
   * Referral attribution code (server-managed; super-admin override only).
   */
  referralCode?: string | null;
  roles?: ('super-admin' | 'user')[] | null;
  tenants?:
    | {
        tenant: string | Tenant;
        id?: string | null;
      }[]
    | null;
  /**
   * Legal/booking first name
   */
  firstName?: string | null;
  /**
   * Legal/booking last name
   */
  lastName?: string | null;
  /**
   * User's location/address
   */
  location?: string | null;
  /**
   * User's country
   */
  country?: string | null;
  /**
   * User's preferred language
   */
  language?: ('en' | 'de' | 'fr' | 'it' | 'es' | 'pt' | 'pl' | 'ro' | 'uk') | null;
  /**
   * Location coordinates with metadata
   */
  coordinates?: {
    /**
     * Location latitude
     */
    lat?: number | null;
    /**
     * Location longitude
     */
    lng?: number | null;
    /**
     * City name from IP geolocation
     */
    city?: string | null;
    /**
     * Country ISO code (e.g., DE, US)
     */
    countryISO?: string | null;
    /**
     * Full country name (e.g., Germany, United States)
     */
    countryName?: string | null;
    /**
     * Region/state name from IP geolocation
     */
    region?: string | null;
    /**
     * Postal/ZIP code
     */
    postalCode?: string | null;
    /**
     * Street address
     */
    street?: string | null;
    /**
     * House number from Google Places
     */
    streetNumber?: string | null;
    /**
     * Whether coordinates were detected from IP
     */
    ipDetected?: boolean | null;
    /**
     * Whether coordinates were manually set by user
     */
    manuallySet?: boolean | null;
  };
  /**
   * Whether the user has completed onboarding
   */
  onboardingCompleted?: boolean | null;
  /**
   * When the customer onboarding email was sent.
   */
  emailNotifiedCustomerOnboardingAt?: string | null;
  /**
   * When the vendor profile created email was sent.
   */
  emailNotifiedVendorCreatedAt?: string | null;
  /**
   * When the user's geolocation was last updated
   */
  geoUpdatedAt?: string | null;
  /**
   * If true, user is blocked platform-wide from creating new bookings until resolved.
   */
  bookingBlocked?: boolean | null;
  bookingBlockedReason?: string | null;
  bookingBlockedAt?: string | null;
  /**
   * Email send status for this user.
   */
  emailDeliverabilityStatus?: ('ok' | 'soft_suppressed' | 'hard_suppressed') | null;
  /**
   * Why the current deliverability status was set.
   */
  emailDeliverabilityReason?: ('complaint' | 'bounce_transient' | 'bounce_permanent' | 'manual') | null;
  /**
   * For soft suppression, resume email sends after this timestamp.
   */
  emailDeliverabilityRetryAfter?: string | null;
  /**
   * Last time deliverability status changed.
   */
  emailDeliverabilityUpdatedAt?: string | null;
  policyAcceptedVersion?: string | null;
  policyAcceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  /**
   * This is the name of the store.
   */
  name: string;
  /**
   * This is the subdomain of the store  (e.g. [slug].yourdomain.com.)
   */
  slug: string;
  image?: (string | null) | Media;
  /**
   * Stripe account ID associated with your shop.
   */
  stripeAccountId: string;
  /**
   * You cannot create products until you submit your stripe details.
   */
  stripeDetailsSubmitted?: boolean | null;
  /**
   * Stripe charges_enabled
   */
  chargesEnabled?: boolean | null;
  /**
   * Stripe payouts_enabled
   */
  payoutsEnabled?: boolean | null;
  onboardingStatus?: ('not_started' | 'in_progress' | 'completed' | 'restricted') | null;
  /**
   * Stripe requirements.currently_due snapshot
   */
  stripeRequirements?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastStripeSyncAt?: string | null;
  /**
   * When the payouts-enabled email was sent.
   */
  emailNotifiedPayoutsEnabledAt?: string | null;
  /**
   * Vendor's bio/description
   */
  bio?: string | null;
  /**
   * Types of services offered
   */
  services?: ('on-site' | 'on-line')[] | null;
  /**
   * Service categories
   */
  categories?: (string | Category)[] | null;
  /**
   * Service subcategories
   */
  subcategories?: (string | Category)[] | null;
  tags?: (string | Tag)[] | null;
  /**
   * Vendor's website URL
   */
  website?: string | null;
  phone?: string | null;
  /**
   * Vendor's hourly rate in EUR
   */
  hourlyRate?: number | null;
  /**
   * Referral attribution copied at tenant creation (super-admin override only).
   */
  referralCode?: string | null;
  /**
   * Two-letter ISO country code (e.g., DE)
   */
  country: string;
  vatRegistered?: boolean | null;
  /**
   * Required if VAT-registered
   */
  vatId?: string | null;
  /**
   * Set by server after VIES check
   */
  vatIdValid?: boolean | null;
  /**
   * The user account associated with this tenant
   */
  user: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  tenant?: (string | null) | Tenant;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  /**
   * Root categories define the work type for the whole category group. Subcategories inherit it from the parent category. This classifies the nature of the work, not the delivery mode.
   */
  workType?: ('manual' | 'consulting' | 'digital') | null;
  color?: string | null;
  /**
   * Optional lucide-react icon name (e.g. 'Car', 'Wrench'). Leave empty for subcategories.
   */
  icon?: string | null;
  parent?: (string | null) | Category;
  subcategories?: {
    docs?: (string | Category)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  tenants?: (string | Tenant)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: string;
  tenant: string | Tenant;
  customer?: (string | null) | User;
  start: string;
  end: string;
  status: 'available' | 'booked' | 'confirmed';
  /**
   * System status: requested → scheduled → completed → accepted | disputed.
   */
  serviceStatus?: ('requested' | 'scheduled' | 'completed' | 'accepted' | 'disputed') | null;
  serviceCompletedAt?: string | null;
  acceptedAt?: string | null;
  disputedAt?: string | null;
  disputeReason?: string | null;
  /**
   * Payment lifecycle: unpaid → pending → paid. Meaningful after service confirmation.
   */
  paymentStatus?: ('unpaid' | 'pending' | 'paid') | null;
  /**
   * Selected service (subcategory) for this booking.
   */
  service?: (string | null) | Category;
  notes?: string | null;
  /**
   * Denormalized display-only snapshot at booking time
   */
  serviceSnapshot?: {
    serviceName?: string | null;
    serviceSlug?: string | null;
    tenantName?: string | null;
    tenantSlug?: string | null;
    hourlyRate?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  status: 'pending' | 'paid' | 'canceled' | 'refunded';
  /**
   * Order-level service lifecycle: requested → scheduled → completed → accepted (or disputed).
   */
  serviceStatus: 'requested' | 'scheduled' | 'completed' | 'accepted' | 'disputed';
  /**
   * Invoice lifecycle: none → draft/issued → overdue/paid (or void).
   */
  invoiceStatus: 'none' | 'draft' | 'issued' | 'void' | 'overdue' | 'paid';
  serviceCompletedAt?: string | null;
  acceptedAt?: string | null;
  disputedAt?: string | null;
  canceledAt?: string | null;
  /**
   * Who triggered the self-service cancellation for this slot-lifecycle order.
   */
  canceledByRole?: ('customer' | 'tenant') | null;
  /**
   * Optional reason captured when a slot-lifecycle order is canceled.
   */
  cancelReason?: string | null;
  invoiceNumber?: string | null;
  invoiceIssuedAt?: string | null;
  paymentDueAt?: string | null;
  paidAt?: string | null;
  user: string | User;
  tenant: string | Tenant;
  /**
   * Booked slots included in this order.
   */
  slots: (string | Booking)[];
  /**
   * Total amount in cents.
   */
  amount: number;
  currency: string;
  /**
   * Platform fee in cents.
   */
  applicationFee?: number | null;
  /**
   * Connected account (Stripe) receiving the funds.
   */
  destination?: string | null;
  /**
   * Stripe Checkout Session ID.
   */
  checkoutSessionId?: string | null;
  /**
   * Stripe Payment Intent ID.
   */
  paymentIntentId?: string | null;
  /**
   * Stripe Balance Transaction ID (optional).
   */
  balanceTxId?: string | null;
  receiptUrl?: string | null;
  /**
   * Optional hold window for UX.
   */
  reservedUntil?: string | null;
  notes?: string | null;
  /**
   * Immutable customer identity captured at checkout time.
   */
  customerSnapshot: {
    firstName: string;
    lastName: string;
    location: string;
    country: string;
    email?: string | null;
  };
  /**
   * Immutable vendor identity captured at checkout time.
   */
  vendorSnapshot: {
    tenantName: string;
    tenantSlug: string;
    stripeAccountId?: string | null;
  };
  /**
   * legacy = old pay-at-booking flow; slot = new slot-lifecycle + partial invoices flow
   */
  lifecycleMode: 'legacy' | 'slot';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: string;
  order: string | Order;
  tenant: string | Tenant;
  customer: string | User;
  status: 'draft' | 'issued' | 'overdue' | 'paid' | 'void';
  currency: string;
  /**
   * Subtotal in minor units (cents).
   */
  amountSubtotalCents: number;
  /**
   * VAT amount in minor units (cents).
   */
  vatAmountCents: number;
  /**
   * Total in minor units (cents).
   */
  amountTotalCents: number;
  /**
   * Applied platform fee rate (bps) for this invoice payment.
   */
  platformFeeRateBps?: number | null;
  /**
   * Applied platform fee amount in cents.
   */
  platformFeeCents?: number | null;
  /**
   * Rule identifier used to compute the platform fee.
   */
  platformFeeRuleId?: string | null;
  /**
   * When the platform fee snapshot was computed for checkout.
   */
  platformFeeCalculatedAt?: string | null;
  /**
   * Commission basis type. Locked to net for MVP.
   */
  platformFeeBasis?: 'net' | null;
  /**
   * Basis amount in cents used for fee calculation.
   */
  platformFeeBasisCents?: number | null;
  /**
   * Applied promotion id, if a promotion was used.
   */
  promotionId?: (string | null) | Promotion;
  /**
   * Reservation/allocation record used for first_n promotions.
   */
  promotionAllocationId?: (string | null) | PromotionAllocation;
  /**
   * Promotion type used for this invoice, when applicable.
   */
  promotionType?: ('first_n' | 'time_window_rate') | null;
  sellerCountryISO: string;
  sellerVatRegistered: boolean;
  sellerVatId?: string | null;
  /**
   * VAT rate in basis points (e.g. 1900 = 19%).
   */
  vatRateBps: number;
  sellerLegalName: string;
  sellerAddressLine1: string;
  sellerCity: string;
  sellerPostal: string;
  sellerEmail?: string | null;
  buyerName: string;
  buyerAddressLine1: string;
  buyerCity: string;
  buyerPostal: string;
  buyerCountryISO: string;
  buyerEmail?: string | null;
  vatPolicy?: string | null;
  lineItems?:
    | {
        slotId: string;
        title: string;
        qty: number;
        unitAmountCents: number;
        amountCents: number;
        start: string;
        end?: string | null;
        id?: string | null;
      }[]
    | null;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  issuedAt?: string | null;
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: string;
  name: string;
  description?: string | null;
  active: boolean;
  type: 'first_n' | 'time_window_rate';
  scope: 'global' | 'tenants' | 'referral';
  priority: number;
  rateBps: number;
  currency: 'eur';
  startsAt?: string | null;
  endsAt?: string | null;
  tenantIds?: (string | Tenant)[] | null;
  referralCode?: string | null;
  /**
   * Copy-ready referral link generated from referralCode.
   */
  referralUrl?: string | null;
  firstNLimit?: number | null;
  firstNScope?: ('global' | 'per_tenant') | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotion_allocations".
 */
export interface PromotionAllocation {
  id: string;
  promotion: string | Promotion;
  counterKey: string;
  /**
   * Unique reservation attempt key to prevent double-reserve on retries.
   */
  reservationKey?: string | null;
  tenant?: (string | null) | Tenant;
  status: 'reserved' | 'consumed' | 'released';
  reservedAt: string;
  consumedAt?: string | null;
  invoice?: (string | null) | Invoice;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  appliedRateBps: number;
  appliedRuleId: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  tenant: string | Tenant;
  tenantSlug: string;
  author: string | User;
  rating: number;
  title: string;
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  tenant: string | Tenant;
  customer: string | User;
  /**
   * Cached from tenant.user for faster filtering and access control.
   */
  tenantUser: string | User;
  status?: ('open' | 'archived' | 'closed') | null;
  lastMessageAt?: string | null;
  lastMessagePreview?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  conversation: string | Conversation;
  senderRole: 'customer' | 'tenant';
  senderUser: string | User;
  text: string;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_profiles".
 */
export interface PaymentProfile {
  id: string;
  user: string | User;
  tenant: string | Tenant;
  userTenantKey: string;
  status: 'missing' | 'active' | 'disabled';
  /**
   * Connected account ID (acct_...) for this tenant.
   */
  stripeAccountId?: string | null;
  stripeCustomerId?: string | null;
  defaultPaymentMethodId?: string | null;
  cardBrand?: string | null;
  cardLast4?: string | null;
  cardExpMonth?: number | null;
  cardExpYear?: number | null;
  setupCompletedAt?: string | null;
  lastUsedAt?: string | null;
  disabledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email_event_logs".
 */
export interface EmailEventLog {
  id: string;
  /**
   * Domain event key, e.g. invoice.issued.customer
   */
  eventType: string;
  entityType: 'order' | 'booking' | 'invoice' | 'message' | 'user' | 'tenant';
  entityId: string;
  /**
   * Optional: link to the Payload user recipient.
   */
  recipientUser?: (string | null) | User;
  toEmail: string;
  dedupeKey: string;
  provider: 'resend';
  /**
   * Message id returned by the provider.
   */
  providerMessageId?: string | null;
  status: 'pending' | 'sent' | 'failed' | 'skipped';
  /**
   * Optional error details for failed sends.
   */
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission_events".
 */
export interface CommissionEvent {
  id: string;
  tenant: string | Tenant;
  invoice: string | Invoice;
  currency: string;
  feeCents: number;
  rateBps: number;
  ruleId: string;
  paymentIntentId: string;
  /**
   * Webhook time when the fee was collected in Stripe.
   */
  collectedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission_statements".
 */
export interface CommissionStatement {
  id: string;
  tenant: string | Tenant;
  periodStart: string;
  periodEnd: string;
  currency: string;
  /**
   * Statement period timezone (locked for MVP).
   */
  timezone: string;
  /**
   * Date basis used to include ledger events.
   */
  basis: string;
  totalsNetCents: number;
  totalsVatCents: number;
  totalsGrossCents: number;
  lineItems?:
    | {
        commissionEvent: string | CommissionEvent;
        feeCents: number;
        paymentIntentId: string;
        collectedAt: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'issued' | 'void' | 'settled';
  statementNumber: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotion_counters".
 */
export interface PromotionCounter {
  id: string;
  /**
   * Unique atomic gate key (e.g. promo:<promotionId>:global or promo:<promotionId>:tenant:<tenantId>).
   */
  counterKey: string;
  promotion: string | Promotion;
  /**
   * Set only for per-tenant counters.
   */
  tenant?: (string | null) | Tenant;
  /**
   * Initialized from promotion at first reservation. Enforced cap for this counter. To change limits, duplicate promotion.
   */
  limit: number;
  used: number;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_chat_threads".
 */
export interface SupportChatThread {
  id: string;
  /**
   * Opaque support-chat continuity id for server/admin correlation; distinct from the Payload document id.
   */
  threadId: string;
  user?: (string | null) | User;
  /**
   * Reserved for future anonymous continuity; not wired by the chat flow yet.
   */
  sessionKey?: string | null;
  locale: 'en' | 'de' | 'fr' | 'it' | 'es' | 'pt' | 'pl' | 'ro' | 'uk';
  status: 'open' | 'escalated' | 'closed';
  lastMessageAt?: string | null;
  lastDisposition?: ('answered' | 'uncertain' | 'escalate' | 'unsupported_account_question') | null;
  lastNeedsHumanSupport?: boolean | null;
  /**
   * Derived from the latest assistant message's structured account-context snapshot.
   */
  lastAccountContextKind?: ('candidate_selection' | 'selected_order' | 'helper_result' | 'payment_overview') | null;
  /**
   * Total stored messages in this support thread. Each completed exchange adds two.
   */
  messageCount: number;
  retentionUntil: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_chat_messages".
 */
export interface SupportChatMessage {
  id: string;
  thread: string | SupportChatThread;
  role: 'user' | 'assistant';
  text: string;
  redactedText?: string | null;
  redactionApplied?: boolean | null;
  redactionTypes?:
    | {
        type: string;
        id?: string | null;
      }[]
    | null;
  locale: 'en' | 'de' | 'fr' | 'it' | 'es' | 'pt' | 'pl' | 'ro' | 'uk';
  responseOrigin: 'server' | 'model';
  disposition?: ('answered' | 'uncertain' | 'escalate' | 'unsupported_account_question') | null;
  needsHumanSupport?: boolean | null;
  model?: string | null;
  modelVersion?: string | null;
  accountAnswerMode?:
    | ('server_deterministic' | 'model_rewritten' | 'model_rewrite_rejected' | 'model_rewrite_disabled')
    | null;
  accountRewriteModel?: string | null;
  accountRewriteModelVersion?: string | null;
  accountRewriteRejectedReason?:
    | (
        | 'feature_disabled'
        | 'model_error'
        | 'empty_output'
        | 'wrong_locale'
        | 'unsafe_system_claim'
        | 'unsupported_fact'
        | 'contradicts_fallback'
        | 'mutation_claim'
        | 'missing_required_limitation'
      )
    | null;
  accountRewriteFallbackUsed?: boolean | null;
  /**
   * Support-safe account/order context shown or used by account-aware support. Do not store raw records or Stripe payloads.
   */
  accountContextSnapshots?:
    | {
        kind: 'candidate_selection' | 'selected_order' | 'helper_result' | 'payment_overview';
        helper?: string | null;
        resultCategory?: string | null;
        statusFilter?: string | null;
        orders?:
          | {
              orderId?: string | null;
              referenceType?: string | null;
              referenceId?: string | null;
              displayReference?: string | null;
              label?: string | null;
              description?: string | null;
              providerDisplayName?: string | null;
              serviceNames?:
                | {
                    name: string;
                    id?: string | null;
                  }[]
                | null;
              firstSlotStart?: string | null;
              createdAt?: string | null;
              serviceStatusCategory?: string | null;
              paymentStatusCategory?: string | null;
              invoiceStatusCategory?: string | null;
              nextStepKey?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  triageIntent?:
    | (
        | 'general_support'
        | 'account_candidate_lookup'
        | 'selected_order_follow_up'
        | 'unsafe_mutation'
        | 'unsupported_account_scope'
        | 'clarify'
        | 'none'
        | 'not_applicable'
      )
    | null;
  triageTopic?: ('booking' | 'payment' | 'cancellation' | 'provider_onboarding') | null;
  triageStatusFilter?: ('requested' | 'scheduled' | 'canceled' | 'paid' | 'payment_pending' | 'payment_not_due') | null;
  triageConfidence?: ('low' | 'medium' | 'high') | null;
  triageReason?: string | null;
  triageMappedHelper?: string | null;
  triageEligibilityAllowed?: boolean | null;
  triageEligibilityReason?:
    | (
        | 'not_signed_in'
        | 'account_aware_disabled'
        | 'low_confidence'
        | 'unsafe_mutation'
        | 'broad_or_deferred'
        | 'unsupported_intent'
        | 'unsupported_topic'
        | 'unsupported_status_filter'
        | 'missing_selected_order'
        | 'no_allowed_mapping'
      )
    | null;
  groundingKind: 'knowledge' | 'account_safe_dto' | 'none';
  promptVersion?: string | null;
  guardrailVersion?: string | null;
  retrievalVersion?: string | null;
  knowledgePackVersion?: string | null;
  openAIRequestId?: string | null;
  sources?:
    | {
        documentId: string;
        documentVersion: string;
        chunkId: string;
        sectionId: string;
        sectionTitle?: string | null;
        sourceType: 'operational-guidance' | 'policy-summary' | 'terms-reference' | 'fallback-guidance';
        sourceLocale: 'en' | 'de' | 'fr' | 'it' | 'es' | 'pt' | 'pl' | 'ro' | 'uk';
        score: number;
        matchedTerms?:
          | {
              term: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'bookings';
        value: string | Booking;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'invoices';
        value: string | Invoice;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'payment_profiles';
        value: string | PaymentProfile;
      } | null)
    | ({
        relationTo: 'email_event_logs';
        value: string | EmailEventLog;
      } | null)
    | ({
        relationTo: 'commission_events';
        value: string | CommissionEvent;
      } | null)
    | ({
        relationTo: 'commission_statements';
        value: string | CommissionStatement;
      } | null)
    | ({
        relationTo: 'promotions';
        value: string | Promotion;
      } | null)
    | ({
        relationTo: 'promotion_counters';
        value: string | PromotionCounter;
      } | null)
    | ({
        relationTo: 'promotion_allocations';
        value: string | PromotionAllocation;
      } | null)
    | ({
        relationTo: 'support_chat_threads';
        value: string | SupportChatThread;
      } | null)
    | ({
        relationTo: 'support_chat_messages';
        value: string | SupportChatMessage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  clerkUsername?: T;
  usernameSource?: T;
  usernameSyncedAt?: T;
  email?: T;
  clerkUserId?: T;
  referralCode?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  firstName?: T;
  lastName?: T;
  location?: T;
  country?: T;
  language?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
        city?: T;
        countryISO?: T;
        countryName?: T;
        region?: T;
        postalCode?: T;
        street?: T;
        streetNumber?: T;
        ipDetected?: T;
        manuallySet?: T;
      };
  onboardingCompleted?: T;
  emailNotifiedCustomerOnboardingAt?: T;
  emailNotifiedVendorCreatedAt?: T;
  geoUpdatedAt?: T;
  bookingBlocked?: T;
  bookingBlockedReason?: T;
  bookingBlockedAt?: T;
  emailDeliverabilityStatus?: T;
  emailDeliverabilityReason?: T;
  emailDeliverabilityRetryAfter?: T;
  emailDeliverabilityUpdatedAt?: T;
  policyAcceptedVersion?: T;
  policyAcceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  workType?: T;
  color?: T;
  icon?: T;
  parent?: T;
  subcategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  stripeAccountId?: T;
  stripeDetailsSubmitted?: T;
  chargesEnabled?: T;
  payoutsEnabled?: T;
  onboardingStatus?: T;
  stripeRequirements?: T;
  lastStripeSyncAt?: T;
  emailNotifiedPayoutsEnabledAt?: T;
  bio?: T;
  services?: T;
  categories?: T;
  subcategories?: T;
  tags?: T;
  website?: T;
  phone?: T;
  hourlyRate?: T;
  referralCode?: T;
  country?: T;
  vatRegistered?: T;
  vatId?: T;
  vatIdValid?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  tenants?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  tenant?: T;
  customer?: T;
  start?: T;
  end?: T;
  status?: T;
  serviceStatus?: T;
  serviceCompletedAt?: T;
  acceptedAt?: T;
  disputedAt?: T;
  disputeReason?: T;
  paymentStatus?: T;
  service?: T;
  notes?: T;
  serviceSnapshot?:
    | T
    | {
        serviceName?: T;
        serviceSlug?: T;
        tenantName?: T;
        tenantSlug?: T;
        hourlyRate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  status?: T;
  serviceStatus?: T;
  invoiceStatus?: T;
  serviceCompletedAt?: T;
  acceptedAt?: T;
  disputedAt?: T;
  canceledAt?: T;
  canceledByRole?: T;
  cancelReason?: T;
  invoiceNumber?: T;
  invoiceIssuedAt?: T;
  paymentDueAt?: T;
  paidAt?: T;
  user?: T;
  tenant?: T;
  slots?: T;
  amount?: T;
  currency?: T;
  applicationFee?: T;
  destination?: T;
  checkoutSessionId?: T;
  paymentIntentId?: T;
  balanceTxId?: T;
  receiptUrl?: T;
  reservedUntil?: T;
  notes?: T;
  customerSnapshot?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        location?: T;
        country?: T;
        email?: T;
      };
  vendorSnapshot?:
    | T
    | {
        tenantName?: T;
        tenantSlug?: T;
        stripeAccountId?: T;
      };
  lifecycleMode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  order?: T;
  tenant?: T;
  customer?: T;
  status?: T;
  currency?: T;
  amountSubtotalCents?: T;
  vatAmountCents?: T;
  amountTotalCents?: T;
  platformFeeRateBps?: T;
  platformFeeCents?: T;
  platformFeeRuleId?: T;
  platformFeeCalculatedAt?: T;
  platformFeeBasis?: T;
  platformFeeBasisCents?: T;
  promotionId?: T;
  promotionAllocationId?: T;
  promotionType?: T;
  sellerCountryISO?: T;
  sellerVatRegistered?: T;
  sellerVatId?: T;
  vatRateBps?: T;
  sellerLegalName?: T;
  sellerAddressLine1?: T;
  sellerCity?: T;
  sellerPostal?: T;
  sellerEmail?: T;
  buyerName?: T;
  buyerAddressLine1?: T;
  buyerCity?: T;
  buyerPostal?: T;
  buyerCountryISO?: T;
  buyerEmail?: T;
  vatPolicy?: T;
  lineItems?:
    | T
    | {
        slotId?: T;
        title?: T;
        qty?: T;
        unitAmountCents?: T;
        amountCents?: T;
        start?: T;
        end?: T;
        id?: T;
      };
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  issuedAt?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  tenant?: T;
  tenantSlug?: T;
  author?: T;
  rating?: T;
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  tenant?: T;
  customer?: T;
  tenantUser?: T;
  status?: T;
  lastMessageAt?: T;
  lastMessagePreview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  senderRole?: T;
  senderUser?: T;
  text?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_profiles_select".
 */
export interface PaymentProfilesSelect<T extends boolean = true> {
  user?: T;
  tenant?: T;
  userTenantKey?: T;
  status?: T;
  stripeAccountId?: T;
  stripeCustomerId?: T;
  defaultPaymentMethodId?: T;
  cardBrand?: T;
  cardLast4?: T;
  cardExpMonth?: T;
  cardExpYear?: T;
  setupCompletedAt?: T;
  lastUsedAt?: T;
  disabledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email_event_logs_select".
 */
export interface EmailEventLogsSelect<T extends boolean = true> {
  eventType?: T;
  entityType?: T;
  entityId?: T;
  recipientUser?: T;
  toEmail?: T;
  dedupeKey?: T;
  provider?: T;
  providerMessageId?: T;
  status?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission_events_select".
 */
export interface CommissionEventsSelect<T extends boolean = true> {
  tenant?: T;
  invoice?: T;
  currency?: T;
  feeCents?: T;
  rateBps?: T;
  ruleId?: T;
  paymentIntentId?: T;
  collectedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission_statements_select".
 */
export interface CommissionStatementsSelect<T extends boolean = true> {
  tenant?: T;
  periodStart?: T;
  periodEnd?: T;
  currency?: T;
  timezone?: T;
  basis?: T;
  totalsNetCents?: T;
  totalsVatCents?: T;
  totalsGrossCents?: T;
  lineItems?:
    | T
    | {
        commissionEvent?: T;
        feeCents?: T;
        paymentIntentId?: T;
        collectedAt?: T;
        id?: T;
      };
  status?: T;
  statementNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  active?: T;
  type?: T;
  scope?: T;
  priority?: T;
  rateBps?: T;
  currency?: T;
  startsAt?: T;
  endsAt?: T;
  tenantIds?: T;
  referralCode?: T;
  referralUrl?: T;
  firstNLimit?: T;
  firstNScope?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotion_counters_select".
 */
export interface PromotionCountersSelect<T extends boolean = true> {
  counterKey?: T;
  promotion?: T;
  tenant?: T;
  limit?: T;
  used?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotion_allocations_select".
 */
export interface PromotionAllocationsSelect<T extends boolean = true> {
  promotion?: T;
  counterKey?: T;
  reservationKey?: T;
  tenant?: T;
  status?: T;
  reservedAt?: T;
  consumedAt?: T;
  invoice?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  appliedRateBps?: T;
  appliedRuleId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_chat_threads_select".
 */
export interface SupportChatThreadsSelect<T extends boolean = true> {
  threadId?: T;
  user?: T;
  sessionKey?: T;
  locale?: T;
  status?: T;
  lastMessageAt?: T;
  lastDisposition?: T;
  lastNeedsHumanSupport?: T;
  lastAccountContextKind?: T;
  messageCount?: T;
  retentionUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_chat_messages_select".
 */
export interface SupportChatMessagesSelect<T extends boolean = true> {
  thread?: T;
  role?: T;
  text?: T;
  redactedText?: T;
  redactionApplied?: T;
  redactionTypes?:
    | T
    | {
        type?: T;
        id?: T;
      };
  locale?: T;
  responseOrigin?: T;
  disposition?: T;
  needsHumanSupport?: T;
  model?: T;
  modelVersion?: T;
  accountAnswerMode?: T;
  accountRewriteModel?: T;
  accountRewriteModelVersion?: T;
  accountRewriteRejectedReason?: T;
  accountRewriteFallbackUsed?: T;
  accountContextSnapshots?:
    | T
    | {
        kind?: T;
        helper?: T;
        resultCategory?: T;
        statusFilter?: T;
        orders?:
          | T
          | {
              orderId?: T;
              referenceType?: T;
              referenceId?: T;
              displayReference?: T;
              label?: T;
              description?: T;
              providerDisplayName?: T;
              serviceNames?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              firstSlotStart?: T;
              createdAt?: T;
              serviceStatusCategory?: T;
              paymentStatusCategory?: T;
              invoiceStatusCategory?: T;
              nextStepKey?: T;
              id?: T;
            };
        id?: T;
      };
  triageIntent?: T;
  triageTopic?: T;
  triageStatusFilter?: T;
  triageConfidence?: T;
  triageReason?: T;
  triageMappedHelper?: T;
  triageEligibilityAllowed?: T;
  triageEligibilityReason?: T;
  groundingKind?: T;
  promptVersion?: T;
  guardrailVersion?: T;
  retrievalVersion?: T;
  knowledgePackVersion?: T;
  openAIRequestId?: T;
  sources?:
    | T
    | {
        documentId?: T;
        documentVersion?: T;
        chunkId?: T;
        sectionId?: T;
        sectionTitle?: T;
        sourceType?: T;
        sourceLocale?: T;
        score?: T;
        matchedTerms?:
          | T
          | {
              term?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}